### ISSUE TITLE
Folder management

### ISSUE THREAD

**Issue by jacyuan** [googleapis/nodejs-resource-manager#349]
Hi,

I'm using NodeJs to develop toolkits for gcp resource managements.

I would like to know if it's planned to support folder management or not in this library (basic CRUD operations of folder for instance). (Or maybe I not in the right place / repository ?)

Thanks a lot.

YL

**Comment by laljikanjareeya** [comment]
@jacyuan you are at right place currently We have only `project` API I will take a look for folder API.

**Comment by jacyuan** [comment]
@laljikanjareeya  ok, nice, thanks for your reply.

**Comment by bcoe** [comment]
Folders should now be supported as of `v3` of the API.
